# Generated by Django 5.2.6 on 2025-09-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('senha', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=70)),
                ('dados_cartao', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empreendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=70, unique=True)),
                ('senha', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=9)),
                ('servico', models.CharField(max_length=45)),
                ('chave_pix', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.cliente')),
                ('metodo_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wavewhiz_app.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='EmpreendedorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.cliente')),
                ('empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.empreendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=40)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.CharField(blank=True, max_length=250, null=True)),
                ('empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.empreendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_final', models.CharField(max_length=45)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.produtos')),
            ],
        ),
    ]
