# Generated by Django 5.2.6 on 2025-09-07 20:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavewhiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Loja',
                'verbose_name_plural': 'Categorias de Loja',
            },
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='empreendedor',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='empreendedor',
            options={'verbose_name': 'Empreendedor', 'verbose_name_plural': 'Empreendedores'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens do Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='metodopagamento',
            options={'verbose_name': 'Método de Pagamento', 'verbose_name_plural': 'Métodos de Pagamento'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dados_cartao',
        ),
        migrations.RemoveField(
            model_name='empreendedor',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='preco_final',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrinho',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=44444444444, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve conter apenas números, entre 8 e 15 dígitos.', regex='^\\d{8,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve conter apenas números, entre 8 e 15 dígitos.', regex='^\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='wavewhiz_app.carrinho'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='lojas/')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wavewhiz_app.categorialoja')),
                ('empreendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.empreendedor')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('descricao', models.TextField(blank=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='wavewhiz_app.loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavewhiz_app.produto'),
        ),
        migrations.DeleteModel(
            name='EmpreendedorCliente',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
