# Generated by Django 5.2.6 on 2025-09-07 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavewhiz_app', '0002_categorialoja_remove_produtos_empreendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('empreendedor', 'Empreendedor')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='wavewhiz_app.Usuario'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='empreendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='wavewhiz_app.Usuario'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empreendedor',
        ),
    ]
