# Generated by Django 5.2.6 on 2025-09-12 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavewhiz_app', '0003_usuario_alter_carrinho_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loja',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('ARTESANATOS', 'Artesanatos'), ('ROUPAS', 'Roupas'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('ARTESANATOS', 'Artesanatos'), ('ROUPAS', 'Roupas'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve conter apenas números, entre 8 e 15 dígitos.', regex='^\\d{8,15}$')]),
        ),
    ]
