# Generated by Django 5.2.6 on 2025-09-15 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavewhiz_app', '0004_usuario_is_staff_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('empreendedor', 'Empreendedor')], max_length=20),
        ),
    ]
