# Generated by Django 5.2.6 on 2025-09-16 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavewhiz_app', '0005_alter_usuario_cpf_alter_usuario_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='categoria',
        ),
        migrations.AddField(
            model_name='loja',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='lojas', to='wavewhiz_app.categorialoja'),
        ),
        migrations.AddField(
            model_name='loja',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 dígitos numéricos.', regex='^\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='loja',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Informe CPF (11 dígitos) ou CNPJ (14 dígitos), somente números.', regex='^(\\d{11}|\\d{14})$')]),
        ),
        migrations.AddField(
            model_name='loja',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve conter exatamente 8 dígitos numéricos.', regex='^\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
