# Generated by Django 5.2.6 on 2025-09-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wavewhiz_app', '0006_remove_loja_categoria_loja_categorias_loja_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rua',
        ),
    ]
