# Generated by Django 5.2.6 on 2025-09-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wavewhiz_app', '0007_remove_usuario_cep_remove_usuario_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
